branchName: '${issue.number}'
defaultBranch: 'develop'
branches: 
  - label:
      - Config
      - DB
      - Doc
      - Feature
    prefix: feature/
  - label: Bugfix
    name: main
    prefix: bugfix/
autoCloseIssue: true
commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'