// database
const DATA_BASE = {
  DATABASE_URL: 'DATABASE_URL',
} as const;

// AWS
const AWS = {
  AWS_ACCESS_KEY: 'AWS_ACCESS_KEY',
  AWS_SECRET_KEY: 'AWS_SECRET_KEY',
  AWS_S3_REGION: 'AWS_S3_REGION',
  AWS_S3_BUCKET_NAME: 'AWS_S3_BUCKET_NAME',
  AWS_S3_ACL: 'AWS_S3_ACL',
  AWS_S3_EXPIRES: 'AWS_S3_EXPIRES',
  AWS_CLOUD_FRONT_URL: 'AWS_CLOUD_FRONT_URL',
} as const;

// git hub
const GIT_HUB = {
  CLIENT_ID_GITHUB: 'CLIENT_ID_GITHUB',
  CLIENT_SECRET_GITHUB: 'CLIENT_SECRET_GITHUB',
} as const;

// discord
const DISCORD = {
  SERVER_EXCEPTION_CHANNEL_URL: 'SERVER_EXCEPTION_CHANNEL_URL',
  NORMAL_NOTIFICATION_CHANNEL_URL: 'NORMAL_NOTIFICATION_CHANNEL_URL',
} as const;

export const ENV_KEY = {
  PORT: 'PORT',
  SECRET_KEY: 'SECRET_KEY',
  NODE_ENV: 'NODE_ENV',
  ...DATA_BASE,
  ...AWS,
  ...GIT_HUB,
  ...DISCORD,
} as const;
