name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  dockerBuild:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: api_server_container_repository
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:latest
  deploy:
    needs: dockerBuild
    name: Deploy
    runs-on: [self-hosted, api-server]
    steps:
      - name: Login to Amazon ECR
        env:
          REGISTRY: ${{ secrets.AWS_ECR_NAME }}
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $REGISTRY
      - name: Docker stop
        run: |
          ids=$(sudo docker ps -a -q)
          for id in $ids
          do
            echo "$id"
            sudo docker stop $id && docker rm $id
          done
          sudo docker system prune -af
      - name: Create env
        env:
          PROJECT_DATABASE_URL: ${{ secrets.PROJECT_DATABASE_URL }}
          PROJECT_PORT: ${{ secrets.PROJECT_PORT }}
          PROJECT_SECRET_KEY: ${{ secrets.PROJECT_SECRET_KEY }}
          PROJECT_AWS_ACCESS_KEY: ${{ secrets.PROJECT_AWS_ACCESS_KEY }}
          PROJECT_AWS_SECRET_KEY: ${{ secrets.PROJECT_AWS_SECRET_KEY }}
          PROJECT_AWS_S3_REGION: ${{ secrets.PROJECT_AWS_S3_REGION }}
          PROJECT_AWS_S3_BUCKET_NAME: ${{ secrets.PROJECT_AWS_S3_BUCKET_NAME }}
          PROJECT_AWS_S3_ACL: ${{ secrets.PROJECT_AWS_S3_ACL }}
          PROJECT_AWS_S3_EXPIRES: ${{ secrets.PROJECT_AWS_S3_EXPIRES }}
        run: |
          sudo rm .env
          touch .env
          echo $PROJECT_DATABASE_URL >> .env
          echo $PROJECT_PORT >> .env
          echo $PROJECT_SECRET_KEY >> .env
          echo $PROJECT_AWS_S3_REGION >> .env
          echo $PROJECT_AWS_S3_BUCKET_NAME >> .env
          echo $PROJECT_AWS_S3_ACL >> .env
          echo $PROJECT_AWS_S3_EXPIRES >> .env
          echo $PROJECT_AWS_ACCESS_KEY >> .env
          echo $PROJECT_AWS_SECRET_KEY >> .env
          cat .env
      - name: Docker run 
        env:
          REGISTRY: ${{ secrets.AWS_ECR_NAME }}
          REPOSITORY: api_server_container_repository
          IMAGE_TAG: latest
          IMAGE_NAME: thepool_nestjs
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
          sudo docker run --env-file ./.env -d -p 80:3000 --name $IMAGE_NAME --restart always $REGISTRY/$REPOSITORY:$IMAGE_TAG
